export const dataForm = {
    id: 0,
    title: '',
    systemName: '',
    blocks: [],
    active: 0,
    createdAt: '',
    embed: '',
    order: 0,
    parentId: null,
    formType: 0,
    options: {},
    updatedAt: '',
    url: '',
    fields: [],
}